apiVersion: v1
kind: ConfigMap
metadata:
  name: payment-config
data:
  DB_HOST: "host.minikube.internal"
  DB_PORT: "5432"
  DB_NAME: "payments_db"
  JWT_ISSUER: "https://auth.local/"
  JWT_AUDIENCE: "payment-service"
  # Payment simulation configuration
  # 0.0 = always success, 0.2 = 20% fail (default), 0.5 = 50% fail, 1.0 = always fail
  PAYMENT_FAILURE_RATE: "0.2"
