apiVersion: v1
kind: ConfigMap
metadata:
  name: catalog-service-config
  namespace: default
data:
  SPRING_DATASOURCE_URL: "jdbc:mysql://host.minikube.internal:3306/catalog_db"
  SPRING_DATASOURCE_USERNAME: "root"
  SPRING_DATASOURCE_PASSWORD: "Root@12345"
