version: "3.8"

services:
  mongo:
    image: mongo:6
    container_name: order-service-mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: order
    volumes:
      - mongo_data:/data/db
    networks:
      - order-network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/order --quiet
      interval: 10s
      timeout: 5s
      retries: 5

  reservation-mock:
    image: node:18-alpine
    container_name: reservation-mock
    working_dir: /app
    volumes:
      - ./src/mocks/reservationMock.js:/app/reservationMock.js
    command: node reservationMock.js
    ports:
      - "3002:3002"
    environment:
      PORT: 3002
    networks:
      - order-network
    depends_on:
      - mongo

  payment-mock:
    image: node:18-alpine
    container_name: payment-mock
    working_dir: /app
    volumes:
      - ./src/mocks/paymentMock.js:/app/paymentMock.js
    command: node paymentMock.js
    ports:
      - "3003:3003"
    environment:
      PORT: 3003
    networks:
      - order-network
    depends_on:
      - mongo

  order-service:
    build: .
    container_name: order-service
    ports:
      - "3001:3001"
    environment:
      MONGO_URI: mongodb://mongo:27017/order
      PORT: 3001
      RESERVATION_SERVICE_URL: http://reservation-mock:3002
      PAYMENT_SERVICE_URL: http://payment-mock:3003
      IDEMPOTENCY_TTL_SECONDS: 3600
      NODE_ENV: development
    depends_on:
      mongo:
        condition: service_healthy
      reservation-mock:
        condition: service_started
      payment-mock:
        condition: service_started
    networks:
      - order-network
    volumes:
      - ./src:/app/src

volumes:
  mongo_data:

networks:
  order-network:
    driver: bridge
